# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d9e834bbcd2621ac5bbcf5848ad98dbb0eae73ba0b9ac252093ed6571ab0239e9b3302cbcc14e5da7afb4b94348c11987e312b32bbedfbbfbce3458f3765005

test:
  secret_key_base: e775dbb3575483ab2e49b8e7ad4290cd645e3a46aa6b2f378275f9c1052527fb32d925425d500e40ec4f2da74ed55f7252342ab344672e167e2831a378e6f605

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
